CREATE TABLE "event" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"google_event_id" text,
	"google_calendar_id" text,
	"ical_uid" text,
	"etag" text,
	"html_link" text,
	"summary" text NOT NULL,
	"description" text,
	"location" text,
	"color_id" text,
	"event_type" text DEFAULT 'default' NOT NULL,
	"status" text DEFAULT 'confirmed' NOT NULL,
	"start_date" text,
	"start_date_time" timestamp,
	"start_time_zone" text,
	"end_date" text,
	"end_date_time" timestamp,
	"end_time_zone" text,
	"end_time_unspecified" boolean DEFAULT false,
	"recurrence" jsonb,
	"recurring_event_id" text,
	"original_start_time" jsonb,
	"visibility" text DEFAULT 'default',
	"transparency" text DEFAULT 'opaque',
	"creator" jsonb,
	"organizer" jsonb,
	"attendees" jsonb,
	"attendees_omitted" boolean DEFAULT false,
	"guests_can_invite_others" boolean DEFAULT true,
	"guests_can_modify" boolean DEFAULT false,
	"guests_can_see_other_guests" boolean DEFAULT true,
	"anyone_can_add_self" boolean DEFAULT false,
	"reminders" jsonb,
	"conference_data" jsonb,
	"hangout_link" text,
	"attachments" jsonb,
	"extended_properties" jsonb,
	"working_location_properties" jsonb,
	"out_of_office_properties" jsonb,
	"focus_time_properties" jsonb,
	"birthday_properties" jsonb,
	"source" jsonb,
	"locked" boolean DEFAULT false,
	"private_copy" boolean DEFAULT false,
	"sequence" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "event" ADD CONSTRAINT "event_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;